In [2]:
import numpy as np
import pandas as pd

In [56]:
main_df = pd.read_csv('full_df.csv',index_col = False)
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
dtypes: int64(10), object(9)
memory usage: 948.9+ KB

In [57]:
Age_Group = []
for value in main_df['Patient Age']:
  if value < 30:
    Age_Group.append('<30')
  elif value < 30:
    Age_Group.append('30-44')
  elif value < 30:
    Age_Group.append('45-59')
  elif value < 75:
    Age_Group.append('60-74')
  else:
    Age_Group.append('> 75')
main_df['Age_Group'] = Age_Group

main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
 19  Age_Group                  6392 non-null   object
dtypes: int64(10), object(10)
memory usage: 998.9+ KB

In [58]:
Primary_Disease = []
main_df['labels'] = [val[2] for val in main_df['labels']]
for value in main_df['labels']:
  if value == "N":
    Primary_Disease.append('Normal')
  elif value == 'D':
    Primary_Disease.append('Diabetes')
  elif value == 'G':
    Primary_Disease.append('Glaucoma')
  elif value == 'C':
    Primary_Disease.append('Cataract')
  elif value == 'A':
    Primary_Disease.append('AMD')
  elif value == 'H':
    Primary_Disease.append('Hypertension')
  elif value == 'M':
    Primary_Disease.append('Myopia')
  elif value == 'O':
    Primary_Disease.append('Other')
  else:
    Primary_Disease.append('Unkown')

main_df['Primary Disease'] = Primary_Disease #NOT_accurate :") but OK, it IS the

main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
 19  Age_Group                  6392 non-null   object
 20  Primary Disease            6392 non-null   object
dtypes: int64(10), object(11)
memory usage: 1.0+ MB

In [59]:
main_df['Disease Count'] = main_df[['N','D','G','C','A','H','M','O']].T.sum()
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
 19  Age_Group                  6392 non-null   object
 20  Primary Disease            6392 non-null   object
 21  Disease Count              6392 non-null   int64
dtypes: int64(11), object(11)
memory usage: 1.1+ MB

In [ ]:
main_df['Disease_Count'][:4]

ID
0    1
1    1
2    2
4    2
Name: Disease_Count, dtype: int64

In [60]:
main_df['Has Comorbidity'] = ["Yes" if value > 1 else "No" for value in main_df['Disease Count']]
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
 19  Age_Group                  6392 non-null   object
 20  Primary Disease            6392 non-null   object
 21  Disease Count              6392 non-null   int64
 22  Has Comorbidity            6392 non-null   object
dtypes: int64(11), object(12)
memory usage: 1.1+ MB

In [61]:
main_df['Eye Side'] = ["Right Eye" if 'right' in value else "Left Eye" for value in main_df['filename']]
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6392 entries, 0 to 6391
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         6392 non-null   int64
 1   Patient Age                6392 non-null   int64
 2   Patient Sex                6392 non-null   object
 3   Left-Fundus                6392 non-null   object
 4   Right-Fundus               6392 non-null   object
 5   Left-Diagnostic Keywords   6392 non-null   object
 6   Right-Diagnostic Keywords  6392 non-null   object
 7   N                          6392 non-null   int64
 8   D                          6392 non-null   int64
 9   G                          6392 non-null   int64
 10  C                          6392 non-null   int64
 11  A                          6392 non-null   int64
 12  H                          6392 non-null   int64
 13  M                          6392 non-null   int64
 14  O                          6392 non-null   int64
 15  filepath                   6392 non-null   object
 16  labels                     6392 non-null   object
 17  target                     6392 non-null   object
 18  filename                   6392 non-null   object
 19  Age_Group                  6392 non-null   object
 20  Primary Disease            6392 non-null   object
 21  Disease Count              6392 non-null   int64
 22  Has Comorbidity            6392 non-null   object
 23  Eye Side                   6392 non-null   object
dtypes: int64(11), object(13)
memory usage: 1.2+ MB

In [53]:
main_df['Eye Side'][:3]

ID
0    Right Eye
1    Right Eye
2    Right Eye
Name: Eye Side, dtype: object

In [11]:
Total_Patients = len(set(main_df['ID']))
Total_Records = len(main_df.index)
Total_Normal_Cases = main_df['N'].sum()
Total_Diabetic_Cases = main_df['D'].sum()
Total_Glaucoma_Cases = main_df['G'].sum()
Total_Cataract_Cases = main_df['C'].sum()
Total_AMD_Cases = main_df['A'].sum()
Total_Hypertension_Cases = main_df['H'].sum()
Total_Myopia_Cases = main_df['M'].sum()
Total_Other_Cases = main_df['O'].sum()

In [13]:
# Disease Prevalence % =
# DIVIDE(
# COUNTROWS('ODIR_Data'),
# CALCULATE(COUNTROWS('ODIR_Data'), ALL('ODIR_Data')),
# 0)  100
"""
Disease Prevalence % = DIVIDE( COUNTROWS('ODIR_Data'), CALCULATE(COUNTROWS('ODIR_Data'), ALL('ODIR_Data')), 0) *100

The provided DAX formula calculates the **percentage of total rows** in the `'ODIR_Data'` table, not a specific disease prevalence rate.

*   **COUNTROWS('ODIR_Data')**: Counts the number of rows in the current filter context (the numerator).
*   **CALCULATE(COUNTROWS('ODIR_Data'), ALL('ODIR_Data'))**: Counts all rows in the table, ignoring any filters (the denominator).
*   **Result**: This expression computes **% of Grand Total** for the current filter context.

To calculate **Disease Prevalence %**, you must restrict the numerator to only the rows where the disease status is positive (e.g., `1` or `"Yes"`). Assuming a column named `'ODIR_Data'[HasDisease]` indicates presence:

```dax
Disease Prevalence % =
DIVIDE(
    CALCULATE(COUNTROWS('ODIR_Data'), 'ODIR_Data'[HasDisease] = 1),
    CALCULATE(COUNTROWS('ODIR_Data'), ALL('ODIR_Data')),
    0
) * 100
```
"""
Normal_Rate = Total_Normal_Cases/ Total_Records * 100
Diabetes_Rate = Total_Diabetic_Cases/ Total_Records * 100
Glaucoma_Rate = Total_Glaucoma_Cases/ Total_Records * 100
Cataract_Rate = Total_Cataract_Cases/ Total_Records * 100
AMD_Rate = Total_AMD_Cases/ Total_Records * 100
Hypertension_Rate = Total_Hypertension_Cases/ Total_Records * 100
Myopia_Rate = Total_Myopia_Cases/ Total_Records * 100

In [28]:
Avg_age = main_df['Patient Age'].mean()
# Avg_age_by_disease = main_df[]

Male_Patients = len(set(main_df[main_df['Patient Sex'] == 'Male']['ID'])) * 100
Female_Patients = len(set(main_df[main_df['Patient Sex'] == 'Female']['ID'])) *100

Male_Percentage = Male_Patients / Total_Patients
Female_Percentage = Female_Patients/ Total_Patients

In [29]:
print(
Total_Patients,'\n',
Total_AMD_Cases,'\n',
Total_Cataract_Cases,'\n',
Total_Diabetic_Cases,'\n',
Total_Glaucoma_Cases,'\n',
Total_Hypertension_Cases,'\n',
Total_Myopia_Cases,'\n',
Total_Hypertension_Cases,'\n',
Total_Normal_Cases,'\n',
Total_Other_Cases,'\n',
Total_Records,'\n',

Avg_age,'\n',

Normal_Rate,'\n',
Diabetes_Rate,'\n',
Glaucoma_Rate,'\n',
Cataract_Rate,'\n',
AMD_Rate,'\n',
Hypertension_Rate,'\n',
Myopia_Rate,'\n',

Male_Patients,'\n',
Female_Patients,'\n',
Male_Percentage,'\n',
Female_Percentage
)

6392
 319
 402
 2123
 397
 203
 306
 203
 2101
 1588
 6392
 57.85794743429287
 32.869211514392994
 33.21339173967459
 6.210888610763455
 6.289111389236545
 4.990613266583229
 3.1758448060075093
 4.787234042553192
 180000
 155800
 28.16020025031289
 24.374217772215268

In [31]:
main_df.isna().sum()

ID                           0
Patient Age                  0
Patient Sex                  0
Left-Fundus                  0
Right-Fundus                 0
Left-Diagnostic Keywords     0
Right-Diagnostic Keywords    0
N                            0
D                            0
G                            0
C                            0
A                            0
H                            0
M                            0
O                            0
filepath                     0
labels                       0
target                       0
filename                     0
Age_Group                    0
Primary Disease              0
Disease Count                0
Has Comorbidity              0
Eye Side                     0
dtype: int64

In [63]:
# main_df['label_target'] = [strng[1:-1].split(', ').index('1') for strng in main_df['target']]
main_df['label_target'] = [val+1 for val in main_df['label_target']]

# main_df = main_df.drop(columns=['filepath','filename','labels','target'])
main_df.to_csv('New_df.csv',index= False)